### ISSUE TITLE
New Rule: image format validation

### ISSUE THREAD

**Issue by malwinq** [ec0lint/ec0lint#26]
### Rule details

accordingly to lighter-image-file of ec0lint-style

### What type of rule is this?

JavaScript/TypeScript code

### Which codebase the rule should be implemented?

base ec0lint

banning all formats except for WebP, SVG, JPG/JPEG, GIF, suggesting WebP and SVG

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

**Comment by malwinq** [comment]
work in progress by @martinabab

**Comment by martinabab** [comment]
task completed, PR: https://github.com/ec0lint/ec0lint/pull/22
