### ISSUE TITLE
New Rule: fonts source validation

### ISSUE THREAD

**Issue by malwinq** [ec0lint/ec0lint#29]
### Rule details

checking if the fonts are built-in or imported from external sources

### What type of rule is this?

Style

### Which codebase the rule should be implemented?

ec0lint-style

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

**Comment by malwinq** [comment]
work in progress by Zyta

**Comment by ec0lint** [comment]
Still an open issue, waiting in backlog to be taken

**Comment by malwinq** [comment]
work in progress by @nemmip

**Comment by malwinq** [comment]
Completed by @nemmip
