### ISSUE TITLE
New Rule: enable lazy loading

### ISSUE THREAD

**Issue by malwinq** [ec0lint/ec0lint#30]
### Rule details

validate if resources always have lazy loading enabled

### What type of rule is this?

Style

### Which codebase the rule should be implemented?

ec0lint-style

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

**Comment by malwinq** [comment]
work in progress by Ania O

**Comment by malwinq** [comment]
Work in progress by @aniagut

**Comment by malwinq** [comment]
to be updated by @aniagut

**Comment by aniagut** [comment]
done in https://github.com/ec0lint/html-ec0lint
