### ISSUE TITLE
New Rule: video format validation

### ISSUE THREAD

**Issue by malwinq** [ec0lint/ec0lint#31]
### Rule details

validate if video formats used in code are the lightest ones

### What type of rule is this?

JavaScript/TypeScript code

### Which codebase the rule should be implemented?

ec0lint

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

**Comment by malwinq** [comment]
work in progress by @martinabab

**Comment by malwinq** [comment]
Work in progress by @martinabab

**Comment by martinabab** [comment]
PR: https://github.com/ec0lint/ec0lint/pull/61
