### ISSUE TITLE
New Rule: image size validation

### ISSUE THREAD

**Issue by malwinq** [ec0lint/ec0lint#39]
### Rule details

checking if an image used on a website has a not too high resolution

### What type of rule is this?

JavaScript/TypeScript code

### Which codebase the rule should be implemented?

ec0lint / ec0lint-style

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

**Comment by malwinq** [comment]
Backlog of release v3.0.0

**Comment by malwinq** [comment]
free to take

**Comment by malwinq** [comment]
In progress by @martinabab

**Comment by martinabab** [comment]
Work in progress 
PR: https://github.com/ec0lint/ec0lint/pull/86

**Comment by martinabab** [comment]
merged PR https://github.com/ec0lint/ec0lint/pull/86
