### ISSUE TITLE
Change Request: change docs url validation

### ISSUE THREAD

**Issue by malwinq** [ec0lint/ec0lint#40]
### ec0lint version

v1.0.0

### What problem do you want to solve?

all docs are currently set to eslint urls

### What do you think is the correct solution?

change of rule regex

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by malwinq** [comment]
Still an open issue, waiting in backlog to be taken

**Comment by malwinq** [comment]
to be updated by @Ola2808-Boro

**Comment by Ola2808-Boro** [comment]
task completed
