### ISSUE TITLE
New Rule: colors control

### ISSUE THREAD

**Issue by malwinq** [ec0lint/ec0lint#42]
### Rule details

checking if the color palette is dark

### What type of rule is this?

Style

### Which codebase the rule should be implemented?

ec0lint-style

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

**Comment by malwinq** [comment]
Backlog of release v4.0.0, research to be done

**Comment by malwinq** [comment]
work in progress by @Ola2808-Boro

**Comment by Ola2808-Boro** [comment]
task completed, PR: 96 ec0lint-style
