### ISSUE TITLE
New Rule: disabling autoplay property

### ISSUE THREAD

**Issue by martinabab** [ec0lint/ec0lint#72]
### Rule details

Disabling the autoplay property in embedded videos' links

### What type of rule is this?

JavaScript/TypeScript code

### Which codebase the rule should be implemented?

ec0lint

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

**Comment by martinabab** [comment]
work in progress by @martinabab

**Comment by martinabab** [comment]
PR: https://github.com/ec0lint/ec0lint/pull/71

**Comment by malwinq** [comment]
to be updated by @martinabab
